 export interface FestivalModel {
  dept_sk: number,
  coordonnees_insee: Array<number>,
  mois_indicatif_en_chiffre_y_compris_double_mois: number,
  date_de_fin_ancien: string,
  nom_departement: string,
  departement: number,
  periodicite: string,
  mois_habituel_de_debut: string,
  code_postal: number,
  domaine: string,
  libelle_commune_pour_calcul_cp_insee: string,
  date_debut_ancien: string,
  code_insee: number,
  region: string,
  commune_principale: string,
  site_web: string,
  nom_de_la_manifestation: string,
  ndeg_identification: string,
  date_de_creation: string,
  check_edition: number,
  ndeg_de_l_edition_2019: number,

 }
